### ISSUE TITLE
code doesn't compile

### ISSUE THREAD

**Issue by puzolabs** [qiscus/qiscus-chat-sdk-flutter-sample#4] opened 2021-09-22 08:30 UTC
hi

trying to compile for android fail with 2 problems:

the first:

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     C:\temp\qiscus-chat-sdk-flutter-sample\build\flutter_downloader\intermediates\library_manifest\debug\AndroidManifest.xml:8:5-12:15: AAPT: error: unexpected element <queries> found in <manifest>.

the second:

C:\Users\Meir.b\Documents\flutter\.pub-cache\hosted\pub.dartlang.org\emoji_picker-0.1.0\android\src\main\java\com\jeffg\emoji_picker\EmojiPickerPlugin.java:3: error: cannot find symbol
import androidx.annotation.NonNull;
                          ^
  symbol:   class NonNull
  location: package androidx.annotation

can you please fix ?

**Comment by apiep** [comment] 2021-09-23 03:14
Hi @puzolabs may I know which flutter version are you using? And also the output of `flutter doctor` too might help

**Comment by puzolabs** [comment] 2021-09-23 05:02
![image](https://user-images.githubusercontent.com/90142257/134456864-90708925-c1e0-4737-9250-05c8d6924f31.png)

**Comment by puzolabs** [comment] 2021-09-23 05:03
i dont think that the problem is the license since other projects that i have compile just great

**Comment by puzolabs** [comment] 2021-09-23 05:03
jdk 16

**Comment by apiep** [comment] 2021-09-23 05:04
Alright, let me take a look at this issue, I think the cause are the left over when I introduce androidx to this sample

**Comment by apiep** [comment] 2021-10-11 12:06
Hi @puzolabs I have pushed the latest changes, can you try again?

It seems like emoji_picker lib which this sample used are no longer maintained, so I have to change it to emoji_picker_flutter which is the updated fork of emoji_picker. And also, I have updated and removed dependencies which required by this sample.

I will close this issue for now, feel free to re-open it if necessary.

**Closed as completed by apiep** 2021-10-11 12:06 UTC
Labels: bug
